a=open('file1.txt','w')
a.write('abc def')
a.write('123 abc')
a.write('111 abc def')
a.close()
f=open('file1.txt','r')
b=f.read()
b=b.replace("abc","")
f.close()
print(b)
a=open('file1.txt','w')
a.write(b)
a.close()
